#!/bin/bash

(cd ${HOME}/AOloop;
rm -rf .apd3k.cacaotaskmanager-log/;   # Loop 5
rm -rf .lowfs3k.cacaotaskmanager-log/; # Loop 6
rm -rf .nir3k.cacaotaskmanager-log/;   # Loop 7
rm -rf .ttoff3k.cacaotaskmanager-log/; # Loop 8
rm -rf .bimdm3kpt.cacaotaskmanager-log/; # Loop 9

cacao-loop-deploy -r ao3k-nirpyr3k; # Loop 7 but also spins up D64 / DM65
cacao-loop-deploy -r ao3k-ttoff3k;  # Loop 8 and spins up DM01 / DM11
cacao-loop-deploy -r ao3k-apd3k;    # Loop 5
cacao-loop-deploy -r ao3k-lowfs3k;  # Loop 6
cacao-loop-deploy -r ao3k-bimdm3kpt; # Loop 9
)
